version: "3.9"

services:
  db:
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    restart: always
    image: postgres:12
    expose:
      - "5432"
    volumes:
      - ./cache/postgresql:/var/lib/postgresql
  backend:
    environment:
      DJANGO_MANAGEPY_MAKEMIGRATION: 1
      DJANGO_MANAGEPY_MIGRATE: 1
      DJANGO_MANAGEPY_COLLECTSTATIC: 1
    env_file:
      - ./app/.env.dev
    build:
      context: ./app
      dockerfile: ./Dockerfile.dev
    links:
      - db:db
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./app/:/app
    logging:
      options:
        max-size: 100m
    # stdin_open: true
    # tty: true
    # command: '/bin/bash'