version: "3.9"

services:
  db:
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    restart: always
    image: postgres:12
    expose:
      - "5432"
    volumes:
      - ./cache/postgresql:/var/lib/postgresql
  backend:
    environment:
      INIT: true

      DEBUG: on
      SECRET_KEY: default

      DATABASE_NAME: db
      DATABASE_ENGINE: django.db.backends.postgresql
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
      DATABASE_HOST: db
    build:
      context: ./app
      dockerfile: ./Dockerfile.dev
    links:
      - db:db
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./app/:/app
    logging:
      options:
        max-size: 100m