---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.name }}-env-secrets
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
{{ toYaml .Values.application.secret_values | indent 2 }}