environments:
  default:
    values:
    - values.yaml

# Repositories
repositories:
- name: jetstack
  url: "https://charts.jetstack.io"
- name: ingress-nginx
  url: "https://kubernetes.github.io/ingress-nginx"
- name: bitnami
  url: "https://charts.bitnami.com/bitnami"

# Releases
releases:

- name: cert-manager
  namespace: security
  createNamespace: true
  labels:
    tier: controller
  chart: jetstack/cert-manager
  version: 1.8.2
  values:
    - charts/{{`{{ .Release.Name }}`}}/values.yaml.gotmpl
  wait: true

- name: ingress-nginx
  namespace: kube-system
  labels:
    tier: ingress
  chart: ingress-nginx/ingress-nginx
  version: 4.1.4

- name: postgresql
  namespace: database
  createNamespace: true
  labels:
    tier: database
  chart: bitnami/postgresql
  version: 11.6.15
  values:
    - charts/{{`{{ .Release.Name }}`}}/values.yaml.gotmpl

- name: application
  namespace: django
  createNamespace: true
  labels:
    tier: application
  chart: ./charts/{{`{{ .Release.Name }}`}}
  missingFileHandler: Warn
  version: 1.0.0
  values:
    - charts/{{`{{ .Release.Name }}`}}/values.yaml.gotmpl
  needs:
    - kube-system/ingress-nginx
    - security/cert-manager
    - database/postgresql
  hooks:
    # Install mkcert CA cert issuer for cert-manager
    - events: ["presync"]
      command: "kubectl"
      args: ["apply", "--validate=true", "--filename=charts/cert-manager/mkcert-ca-issuer.yaml"]
    # Fix https://github.com/kubernetes/ingress-nginx/issues/5401#issuecomment-662424306
    - events: ["presync"]
      command: "kubectl"
      args: ["delete", "-A", "ValidatingWebhookConfiguration", "ingress-nginx-admission"]