project: django

database:
  name: postgresql
  username: bukL7EukgGA
  password: Z6rJKisQmAf
  port: 5432
  settings:
    size: 2Gi

ingress:
  name: ingress-nginx
  namespace: django
  className: nginx

application:
  host: localhost
  name: django
  image: django:local
  replicas: 2
  maxreplicas: 3
  containerPort: 80
  servicePort: 80
  serviceType: ClusterIP
  requests_memory: 200Mi
  requests_cpu: 400m
  limit_memory: 400Mi
  limit_cpu: 800m
  livenessProbe_initialDelaySeconds: 5
  livenessProbe_periodSeconds: 60
  readinessProbe_initialDelaySeconds: 5
  readinessProbe_periodSeconds: 5
  terminationGracePeriodSeconds: 60
  health_check_url: /
  config_map_values:
    DEBUG: "\"off\""

    DATABASE_ENGINE: django.db.backends.postgresql
    DATABASE_HOST: postgresql.database.svc.cluster.local
    DATABASE_PORT: "\"5432\""
    DATABASE_NAME: postgresql

  secret_values:
    SECRET_KEY: "4&yf5g+pd3d=8(5ot!+c)00n_gsma^6&xnxdwb#7-w+p%w863^"

    DATABASE_USERNAME: bukL7EukgGA
    DATABASE_PASSWORD: Z6rJKisQmAf